/* Jade Dragon Quest — Service Worker
 * Cache-first app shell + all pre-rendered word clips, so the game runs
 * fully offline after the first load. The clip list is read from
 * audio/clips.json (generated by tools/gen-audio.js).
 */
const CACHE = 'jdq-v6';

const SHELL = [
  './',
  './index.html',
  './style.css',
  './manifest.json',
  './vocab-data.js',
  './audio.js',
  './progress.js',
  './sidekick.js',
  './levels/level1-metal.js',
  './levels/level2-water.js',
  './levels/level3-wood.js',
  './levels/level4-fire.js',
  './levels/level5-dragon.js',
  './bonus-zodiac.js',
  './app.js',
  './icons/icon.svg',
  './audio/clips.json',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then(async (cache) => {
      // App shell first — one failure shouldn't abort the whole install.
      await Promise.allSettled(SHELL.map((url) => cache.add(url)));
      // Then precache every word clip listed in the manifest.
      try {
        const res = await fetch('./audio/clips.json', { cache: 'no-cache' });
        if (res.ok) {
          const clips = await res.json();
          await Promise.allSettled(clips.map((url) => cache.add('./' + url)));
        }
      } catch (_) { /* clips load lazily at runtime if precache fails */ }
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

function isFont(url) {
  return url.hostname.includes('fonts.googleapis.com') || url.hostname.includes('fonts.gstatic.com');
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  let url;
  try { url = new URL(req.url); } catch (_) { return; }

  // Google Fonts: cache-first runtime caching (opaque responses OK).
  if (isFont(url)) {
    event.respondWith(
      caches.open(CACHE).then(async (cache) => {
        const hit = await cache.match(req);
        if (hit) return hit;
        try {
          const res = await fetch(req);
          if (res && (res.ok || res.type === 'opaque')) cache.put(req, res.clone());
          return res;
        } catch (_) {
          return hit || Response.error();
        }
      })
    );
    return;
  }

  // App shell + clips + same-origin: cache-first, network, then index.html.
  if (url.origin === self.location.origin) {
    event.respondWith(
      caches.match(req).then((hit) => {
        if (hit) return hit;
        return fetch(req)
          .then((res) => {
            if (res && res.ok) {
              const copy = res.clone();
              caches.open(CACHE).then((c) => c.put(req, copy));
            }
            return res;
          })
          .catch(() => {
            if (req.mode === 'navigate') return caches.match('./index.html');
            return Response.error();
          });
      })
    );
  }
});
